import type { Livro, NewLivro } from "@/lib/types";


export const fakeLivrosNovos: NewLivro[] = [
  {
    titulo: "Cálculo Estrutural Avançado",
    slug: "calculo-estrutural-avancado",
    categoria: "Engenharia Civil",
    descricao: "Um guia completo sobre estruturas de concreto e aço para grandes obras.",
    status: "publicado",
    autor: "Dr. Ricardo Santos",
    anoPublicacao: 2023,
    detalhes: {
      sinopse: "Aborda desde os fundamentos até as normas técnicas mais recentes.",
      numeroPaginas: 450,
      autor: "Dr. Ricardo Santos",
      editora: "TechPress",
      isbn: "978-85-000-0001-1",
    },
    midia: {
      capa: "https://exemplo.com/capas/calculo.jpg",
      pdf: "https://exemplo.com/files/calculo.pdf",
    },
    areas: ["estruturas", "concreto_armado"],
    macroAreas: ["Civil"],
    tags: ["engenharia", "calculo", "concreto"],
    novo: true,
    popular: true,
  },
  {
    titulo: "Algoritmos e Estruturas de Dados",
    slug: "algoritmos-estruturas-dados",
    categoria: "Computação",
    descricao: "A bíblia para entender a base da programação eficiente.",
    status: "publicado",
    autor: "Ana Clara Oliveira",
    anoPublicacao: 2022,
    detalhes: {
      numeroPaginas: 320,
      autor: "Ana Clara Oliveira",
      editora: "CodeMasters",
    },
    midia: {
      capa: "https://exemplo.com/capas/algoritmos.png",
      epub: "https://exemplo.com/files/algoritmos.epub",
    },
    areas: ["algoritmos", "estruturas_de_dados"],
    macroAreas: ["Computacao"],
    tags: ["programação", "backend"],
    novo: false,
    popular: true,
  },
  {
    titulo: "Física Quântica para Iniciantes",
    slug: "fisica-quantica-iniciantes",
    categoria: "Física",
    descricao: "Conceitos complexos explicados de forma simples e direta.",
    status: "publicado",
    autor: "Prof. Alberto Einstein",
    detalhes: {
      sinopse: "Uma jornada pelo mundo das partículas subatômicas.",
      numeroPaginas: 180,
      autor: "Prof. Alberto Einstein",
    },
    midia: {
      capa: "https://exemplo.com/capas/fisica.jpg",
    },
    areas: ["fisica_moderna"],
    macroAreas: ["Fisica"],
    tags: ["ciencia", "quântica"],
  },
  {
    titulo: "Introdução ao Controle Automático",
    slug: "introducao-controle-automatico",
    categoria: "Automação",
    descricao: "Fundamentos de sistemas de controle e realimentação.",
    status: "rascunho",
    autor: "Eng. Marcos Viana",
    detalhes: {
      numeroPaginas: 290,
      autor: "Eng. Marcos Viana",
      editora: "Industrial Book",
    },
    midia: {
      capa: "https://exemplo.com/capas/controle.jpg",
      pdf: "https://exemplo.com/files/controle.pdf",
    },
    areas: ["controle_automatico", "sistemas_de_controle"],
    macroAreas: ["Controle_automacao"],
    tags: ["automacao", "sistemas"],
  },
  {
    titulo: "Química Orgânica Experimental",
    slug: "quimica-organica-experimental",
    categoria: "Química",
    descricao: "Manual de laboratório para síntese de compostos orgânicos.",
    status: "publicado",
    autor: "Dra. Beatriz Luz",
    anoPublicacao: 2021,
    detalhes: {
      numeroPaginas: 215,
      autor: "Dra. Beatriz Luz",
      isbn: "978-85-111-2222-3",
    },
    midia: {
      capa: "https://exemplo.com/capas/quimica.png",
      resumo: "https://exemplo.com/resumos/quimica.pdf",
    },
    areas: ["quimica_organica"],
    macroAreas: ["Quimica"],
    tags: ["laboratorio", "quimica"],
  },
  {
    titulo: "Desenvolvimento Web com React",
    slug: "dev-web-react",
    categoria: "Programação",
    descricao: "Aprenda a criar interfaces modernas e performáticas.",
    status: "pendente",
    autor: "Lucas Frontend",
    detalhes: {
      numeroPaginas: 400,
      autor: "Lucas Frontend",
      editora: "WebFlow Edições",
    },
    midia: {
      capa: "https://exemplo.com/capas/react.jpg",
      epub: "",
    },
    areas: ["web", "programacao"],
    macroAreas: ["Programacao", "Computacao"],
    tags: ["react", "javascript", "frontend"],
  },
  {
    titulo: "Termodinâmica para Engenheiros",
    slug: "termodinamica-engenheiros",
    categoria: "Mecânica",
    descricao: "Estudo das leis da termodinâmica aplicadas a máquinas térmicas.",
    status: "publicado",
    autor: "Carlos Termo",
    detalhes: {
      numeroPaginas: 510,
      autor: "Carlos Termo",
    },
    midia: {
      capa: "https://exemplo.com/capas/termo.jpg",
    },
    areas: ["termodinamica", "maquinas_termicas"],
    macroAreas: ["Fisica", "Mecanica"],
    tags: ["energia", "calor"],
  },
  {
    titulo: "Segurança em Redes Sem Fio",
    slug: "seguranca-redes-wireless",
    categoria: "Cyber Segurança",
    descricao: "Protocolos e ataques em ambientes Wi-Fi.",
    status: "arquivado",
    autor: "Hacker do Bem",
    detalhes: {
      numeroPaginas: 150,
      autor: "Hacker do Bem",
      isbn: null,
    },
    midia: {
      capa: "https://exemplo.com/capas/seguranca.jpg",
      pdf: "https://exemplo.com/files/seguranca.pdf",
    },
    areas: ["seguranca_da_informacao", "redes_de_computadores"],
    macroAreas: ["Cyber_seguranca", "Redes_de_computadores"],
    tags: ["security", "wifi"],
  },
  {
    titulo: "Inteligência Artificial na Prática",
    slug: "ia-na-pratica",
    categoria: "IA",
    descricao: "Implementando modelos de Machine Learning do zero.",
    status: "publicado",
    autor: "Sofia Neural",
    anoPublicacao: 2024,
    detalhes: {
      sinopse: "Focado em aplicações reais de IA no mercado.",
      numeroPaginas: 380,
      autor: "Sofia Neural",
    },
    midia: {
      capa: "https://exemplo.com/capas/ia.jpg",
    },
    areas: ["inteligencia_artificial", "aprendizado_de_maquina"],
    macroAreas: ["IA"],
    tags: ["python", "ml", "ia"],
    popular: true,
  },
  {
    titulo: "Circuitos Elétricos I",
    slug: "circuitos-eletricos-1",
    categoria: "Elétrica",
    descricao: "Análise de circuitos CC e CA para graduação.",
    status: "publicado",
    autor: "Prof. Ohm",
    detalhes: {
      numeroPaginas: 600,
      autor: "Prof. Ohm",
      editora: "Volt Books",
    },
    midia: {
      capa: "https://exemplo.com/capas/circuitos.jpg",
      pdf: "https://exemplo.com/files/circuitos.pdf",
    },
    areas: ["circuitos_eletricos", "eletricidade"],
    macroAreas: ["Eletrica"],
    tags: ["eletrica", "engenharia"],
    novo: false,
  },
];


// Dados simulados do banco de dados:
export const fakeSelectLivros: Livro[] = [
  {
    id: 1,
    titulo: "Cálculo Estrutural Avançado",
    slug: "calculo-estrutural-avancado",
    categoria: "Engenharia Civil",
    descricao: "Um guia completo sobre estruturas de concreto e aço.",
    status: "publicado",
    autor: "Dr. Ricardo Santos",
    anoPublicacao: 2023,
    idioma: "Português",
    views: 1250,
    downloads: 450,
    avaliacao: "4.8",
    detalhes: {
      sinopse: "Aborda desde os fundamentos até as normas técnicas mais recentes.",
      numeroPaginas: 450,
      autor: "Dr. Ricardo Santos",
      editora: "TechPress",
      isbn: "978-85-000-0001-1",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1544947950-fa07a98d237f",
      pdf: "https://exemplo.com/files/calculo.pdf",
    },
    areas: ["estruturas", "concreto_armado"],
    macroAreas: ["Civil"],
    tags: ["engenharia", "calculo", "concreto"],
    novo: false,
    popular: true,
    createdAt: new Date("2024-01-10T10:00:00Z"),
    updatedAt: new Date("2024-01-15T14:30:00Z"),
  },
  {
    id: 2,
    titulo: "Algoritmos e Estruturas de Dados",
    slug: "algoritmos-estruturas-dados",
    categoria: "Computação",
    descricao: "A bíblia para entender a base da programação eficiente.",
    status: "publicado",
    autor: "Ana Clara Oliveira",
    anoPublicacao: 2022,
    idioma: "Português",
    views: 8900,
    downloads: 2100,
    avaliacao: "4.9",
    detalhes: {
      numeroPaginas: 320,
      autor: "Ana Clara Oliveira",
      editora: "CodeMasters",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
      epub: "https://exemplo.com/files/algoritmos.epub",
    },
    areas: ["algoritmos", "estruturas_de_dados"],
    macroAreas: ["Computacao"],
    tags: ["programação", "backend", "logica"],
    novo: false,
    popular: true,
    createdAt: new Date("2023-11-20T08:00:00Z"),
    updatedAt: new Date("2023-11-20T08:00:00Z"),
  },
  {
    id: 3,
    titulo: "Física Quântica para Iniciantes",
    slug: "fisica-quantica-iniciantes",
    categoria: "Física",
    descricao: "Conceitos complexos explicados de forma simples.",
    status: "publicado",
    autor: "Prof. Alberto Einstein",
    anoPublicacao: 2021,
    idioma: "Inglês",
    views: 540,
    downloads: 120,
    avaliacao: "4.5",
    detalhes: {
      sinopse: "Uma jornada pelo mundo das partículas subatômicas.",
      numeroPaginas: 180,
      autor: "Prof. Alberto Einstein",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb",
    },
    areas: ["fisica_moderna"],
    macroAreas: ["Fisica"],
    tags: ["ciencia", "quântica"],
    novo: true,
    popular: false,
    createdAt: new Date("2024-02-01T12:00:00Z"),
    updatedAt: new Date("2024-02-01T12:00:00Z"),
  },
  {
    id: 4,
    titulo: "Introdução ao Controle Automático",
    slug: "introducao-controle-automatico",
    categoria: "Automação",
    descricao: "Fundamentos de sistemas de controle e realimentação.",
    status: "rascunho",
    autor: "Eng. Marcos Viana",
    anoPublicacao: 2024,
    idioma: "Português",
    views: 45,
    downloads: 2,
    avaliacao: "0",
    detalhes: {
      numeroPaginas: 290,
      autor: "Eng. Marcos Viana",
      editora: "Industrial Book",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1518314916381-77a37c2a49ae",
      pdf: "https://exemplo.com/files/controle.pdf",
    },
    areas: ["controle_automatico", "sistemas_de_controle"],
    macroAreas: ["Controle_automacao"],
    tags: ["automacao", "sistemas"],
    novo: true,
    popular: false,
    createdAt: new Date("2024-03-05T09:15:00Z"),
    updatedAt: new Date("2024-03-05T09:15:00Z"),
  },
  {
    id: 5,
    titulo: "Química Orgânica Experimental",
    slug: "quimica-organica-experimental",
    categoria: "Química",
    descricao: "Manual de laboratório para síntese de compostos.",
    status: "publicado",
    autor: "Dra. Beatriz Luz",
    anoPublicacao: 2020,
    idioma: "Português",
    views: 2300,
    downloads: 800,
    avaliacao: "4.7",
    detalhes: {
      numeroPaginas: 215,
      autor: "Dra. Beatriz Luz",
      isbn: "978-85-111-2222-3",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1532187875605-1ef6c756999a",
      resumo: "https://exemplo.com/resumos/quimica.pdf",
    },
    areas: ["quimica_organica"],
    macroAreas: ["Quimica"],
    tags: ["laboratorio", "quimica"],
    novo: false,
    popular: true,
    createdAt: new Date("2023-05-10T14:00:00Z"),
    updatedAt: new Date("2023-06-12T10:30:00Z"),
  },
  {
    id: 6,
    titulo: "Desenvolvimento Web com React",
    slug: "dev-web-react",
    categoria: "Programação",
    descricao: "Aprenda a criar interfaces modernas e performáticas.",
    status: "publicado",
    autor: "Lucas Frontend",
    anoPublicacao: 2024,
    idioma: "Português",
    views: 15400,
    downloads: 6700,
    avaliacao: "5.0",
    detalhes: {
      numeroPaginas: 400,
      autor: "Lucas Frontend",
      editora: "WebFlow Edições",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1633356122544-f134324a6cee",
      epub: "",
    },
    areas: ["web", "programacao"],
    macroAreas: ["Programacao", "Computacao"],
    tags: ["react", "javascript", "frontend"],
    novo: true,
    popular: true,
    createdAt: new Date("2024-01-20T11:00:00Z"),
    updatedAt: new Date("2024-01-20T11:00:00Z"),
  },
  {
    id: 7,
    titulo: "Termodinâmica para Engenheiros",
    slug: "termodinamica-engenheiros",
    categoria: "Mecânica",
    descricao: "Estudo das leis da termodinâmica em máquinas térmicas.",
    status: "publicado",
    autor: "Carlos Termo",
    anoPublicacao: 2019,
    idioma: "Espanhol",
    views: 3100,
    downloads: 900,
    avaliacao: "4.2",
    detalhes: {
      numeroPaginas: 510,
      autor: "Carlos Termo",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1581092160562-40aa08e78837",
    },
    areas: ["termodinamica", "maquinas_termicas"],
    macroAreas: ["Fisica", "Mecanica"],
    tags: ["energia", "calor", "motores"],
    novo: false,
    popular: false,
    createdAt: new Date("2022-08-15T16:00:00Z"),
    updatedAt: new Date("2022-08-15T16:00:00Z"),
  },
  {
    id: 8,
    titulo: "Segurança em Redes Sem Fio",
    slug: "seguranca-redes-wireless",
    categoria: "Cyber Segurança",
    descricao: "Protocolos e ataques em ambientes Wi-Fi.",
    status: "arquivado",
    autor: "Hacker do Bem",
    anoPublicacao: 2021,
    idioma: "Inglês",
    views: 120,
    downloads: 30,
    avaliacao: "3.5",
    detalhes: {
      numeroPaginas: 150,
      autor: "Hacker do Bem",
      isbn: null,
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b",
      pdf: "https://exemplo.com/files/seguranca.pdf",
    },
    areas: ["seguranca_da_informacao", "redes_de_computadores"],
    macroAreas: ["Cyber_seguranca", "Redes_de_computadores"],
    tags: ["security", "wifi"],
    novo: false,
    popular: false,
    createdAt: new Date("2023-12-01T08:00:00Z"),
    updatedAt: new Date("2023-12-01T08:00:00Z"),
  },
  {
    id: 9,
    titulo: "Inteligência Artificial na Prática",
    slug: "ia-na-pratica",
    categoria: "IA",
    descricao: "Implementando modelos de Machine Learning do zero.",
    status: "publicado",
    autor: "Sofia Neural",
    anoPublicacao: 2024,
    idioma: "Português",
    views: 21000,
    downloads: 12000,
    avaliacao: "4.9",
    detalhes: {
      sinopse: "Focado em aplicações reais de IA no mercado.",
      numeroPaginas: 380,
      autor: "Sofia Neural",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1677442136019-21780ecad995",
    },
    areas: ["inteligencia_artificial", "aprendizado_de_maquina"],
    macroAreas: ["IA"],
    tags: ["python", "ml", "ia"],
    novo: true,
    popular: true,
    createdAt: new Date("2024-01-05T15:00:00Z"),
    updatedAt: new Date("2024-02-10T12:00:00Z"),
  },
  {
    id: 10,
    titulo: "Circuitos Elétricos I",
    slug: "circuitos-eletricos-1",
    categoria: "Elétrica",
    descricao: "Análise de circuitos CC e CA para graduação.",
    status: "publicado",
    autor: "Prof. Ohm",
    anoPublicacao: 2022,
    idioma: "Português",
    views: 4500,
    downloads: 1100,
    avaliacao: "4.6",
    detalhes: {
      numeroPaginas: 600,
      autor: "Prof. Ohm",
      editora: "Volt Books",
    },
    midia: {
      capa: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0",
      pdf: "https://exemplo.com/files/circuitos.pdf",
    },
    areas: ["circuitos_eletricos", "eletricidade"],
    macroAreas: ["Eletrica"],
    tags: ["eletrica", "engenharia", "circuitos"],
    novo: false,
    popular: true,
    createdAt: new Date("2023-01-15T10:00:00Z"),
    updatedAt: new Date("2023-01-15T10:00:00Z"),
  },
];