CREATE TYPE "public"."tipo" AS ENUM('livro', 'software', 'projeto', 'artigo');--> statement-breakpoint
CREATE TABLE "livros" (
	"id" serial PRIMARY KEY NOT NULL,
	"titulo" text NOT NULL,
	"slug" text NOT NULL,
	"categoria" text NOT NULL,
	"descricao" text NOT NULL,
	"status" text DEFAULT 'rascunho' NOT NULL,
	"views" integer DEFAULT 0,
	"downloads" integer DEFAULT 0,
	"avaliacao" numeric DEFAULT '0',
	"autor" text NOT NULL,
	"isbn" text,
	"ano_publicacao" integer,
	"editora" text,
	"idioma" text,
	"numero_paginas" integer,
	"detalhes" jsonb NOT NULL,
	"midia" jsonb NOT NULL,
	"areas" jsonb NOT NULL,
	"macro_areas" jsonb NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "livros_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "softwares" (
	"id" serial PRIMARY KEY NOT NULL,
	"titulo" text NOT NULL,
	"slug" text NOT NULL,
	"categoria" text NOT NULL,
	"descricao" text NOT NULL,
	"status" text DEFAULT 'rascunho' NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"downloads" integer DEFAULT 0 NOT NULL,
	"avaliacao" numeric DEFAULT '0' NOT NULL,
	"site_oficial" text NOT NULL,
	"funcionalidades" text,
	"requisitos" text,
	"preco" text NOT NULL,
	"plataformas" jsonb NOT NULL,
	"screenshots" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tutorial_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "softwares_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "projetos" (
	"id" serial PRIMARY KEY NOT NULL,
	"titulo" text NOT NULL,
	"slug" text NOT NULL,
	"categoria" text NOT NULL,
	"descricao" text NOT NULL,
	"status" text DEFAULT 'rascunho' NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"downloads" integer DEFAULT 0 NOT NULL,
	"avaliacao" numeric DEFAULT '0' NOT NULL,
	"autor" text NOT NULL,
	"problema_resolvido" text NOT NULL,
	"tecnologias" text NOT NULL,
	"repositorio_github" text,
	"documentacao_url" text,
	"imagens_url" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"dificuldade" text NOT NULL,
	"duracao" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "projetos_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "artigos" (
	"id" serial PRIMARY KEY NOT NULL,
	"titulo" text NOT NULL,
	"slug" text NOT NULL,
	"categoria" text NOT NULL,
	"descricao" text NOT NULL,
	"status" text DEFAULT 'rascunho' NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"downloads" integer DEFAULT 0 NOT NULL,
	"avaliacao" numeric DEFAULT '0' NOT NULL,
	"autores" text NOT NULL,
	"resumo" text NOT NULL,
	"palavras_chave" text,
	"ano_publicacao" integer,
	"instituicao" text,
	"areas" jsonb NOT NULL,
	"macro_areas" jsonb NOT NULL,
	"midia" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "artigos_slug_unique" UNIQUE("slug")
);
